# 指定 pipeline，且由 docker runner 執行
kind: pipeline
type: exec
name: deploy_service

platform:
  os: linux
  arch: amd64

# for build code 使用，clone 時抓 depth = 1 即可，加快速度
clone:
  depth: 1

# 這邊開始定義 pipeline 的每個步驟
steps:
  - name: teardown-existing-services
    commands:
      - cd /home/wayne011872/side_project/devop
      - docker-compose down web-svc
      - docker-compose rm -f web-svc
      - docker rmi -f web:dev
    when:
      branch:
        - develop

  - name: run-make-command
    commands:
      - cd /home/wayne011872/side_project/side_project_web
      - git config --global --add safe.directory /home/wayne011872/side_project/side_project_web
      - git pull origin develop
      - make build-docker-img
    when:
      branch:
      - develop

  - name: setup-services
    commands:
      - cd /home/wayne011872/side_project/devop
      - docker-compose up -d web-svc
    when:
      branch:
        - develop
trigger:
  branch:
  - develop
  event:
  - push
  - pull_request